# PLANS = [
#     ('FREELANCE', 'FREELANCE'),
#     ('EDUCATIONAL TIER 1', 'EDUCATIONAL TIER 1'),
#     ('EDUCATIONAL TIER 2', 'EDUCATIONAL TIER 2'),
#     ('WORKSPACE TIER 1', 'WORKSPACE TIER 1'),
#     ('WORKSPACE TIER 2', 'WORKSPACE TIER 2'),
# ]