# Generated by Django 3.1.2 on 2020-11-12 00:31

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('fullName', models.CharField(max_length=20, verbose_name='Full Name')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profilepictures/', verbose_name='Profile Picture')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('organization', models.CharField(help_text='write full form of the organization', max_length=75, verbose_name='Organization')),
                ('occupation', models.CharField(choices=[('Actor', 'Actor'), ('Architecture', 'Architecture'), ('Armed Forces', 'Armed Forces'), ('Artisan', 'Artisan'), ('Automobile', 'Automobile'), ('Construction', 'Construction'), ('Dancer', 'Dancer'), ('Design and Creativity', 'Design and Creativity'), ('Education', 'Education'), ('Engineering', 'Engineering'), ('Farming', 'Farming'), ('Finance', 'Finance'), ('Fine Arts', 'Fine Arts'), ('Food and Services', 'Food and Services'), ('Human Resources', 'Human Resources'), ('Information Technology', 'Information Technology'), ('Judiciary', 'Judiciary'), ('Legislation ', 'Legislation '), ('Marketing', 'Marketing'), ('Medical', 'Medical'), ('Medical practitioner', 'Medical practitioner'), ('Musician', 'Musician'), ('Nursing Staff', 'Nursing Staff'), ('Pharmacist', 'Pharmacist'), ('Producer', 'Producer'), ('Public health executive', 'Public health executive'), ('Researcher', 'Researcher'), ('Sales', 'Sales'), ('Social Sciences', 'Social Sciences'), ('Water supply', 'Water supply'), ('Wood and metalwork', 'Wood and metalwork'), ('Writer', 'Writer')], max_length=100, verbose_name='Occupation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserProfile',
                'verbose_name_plural': 'UserProfiles',
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(choices=[('Agriculture', 'Agriculture'), ('Arts and Entertainment', 'Arts and Entertainment'), ('Education', 'Education'), ('Food', 'Food'), ('Hardware and Automobiles', 'Hardware and Automobiles'), ('Healthcare and Medicine', 'Healthcare and Medicine'), ('Law and Enforcement', 'Law and Enforcement'), ('Sales and Management', 'Sales and Management'), ('Science and Technology', 'Science and Technology')], max_length=100, verbose_name='Interest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interest',
                'verbose_name_plural': 'Interests',
            },
        ),
    ]
