# Generated by Django 3.1.2 on 2020-11-11 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='firstName',
            new_name='fullName',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastName',
        ),
    ]
