# Generated by Django 3.1.2 on 2020-11-09 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201102_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('organization', models.CharField(max_length=75, verbose_name='Organization')),
                ('occupation', models.CharField(choices=[('Actor', 'Actor'), ('Architecture', 'Architecture'), ('Armed Forces', 'Armed Forces'), ('Artisan', 'Artisan'), ('Automobile', 'Automobile'), ('Construction', 'Construction'), ('Dancer', 'Dancer'), ('Design and Creativity', 'Design and Creativity'), ('Education', 'Education'), ('Engineering', 'Engineering'), ('Farming', 'Farming'), ('Finance', 'Finance'), ('Fine Arts', 'Fine Arts'), ('Food and Services', 'Food and Services'), ('Human Resources', 'Human Resources'), ('Information Technology', 'Information Technology'), ('Judiciary', 'Judiciary'), ('Legislation ', 'Legislation '), ('Marketing', 'Marketing'), ('Medical', 'Medical'), ('Medical practitioner', 'Medical practitioner'), ('Musician', 'Musician'), ('Nursing Staff', 'Nursing Staff'), ('Pharmacist', 'Pharmacist'), ('Producer', 'Producer'), ('Public health executive', 'Public health executive'), ('Researcher', 'Researcher'), ('Sales', 'Sales'), ('Social Sciences', 'Social Sciences'), ('Water supply', 'Water supply'), ('Wood and metalwork', 'Wood and metalwork'), ('Writer', 'Writer')], max_length=100, verbose_name='Occupation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserProfile',
                'verbose_name_plural': 'UserProfiles',
            },
        ),
    ]
