# Generated by Django 3.1.2 on 2020-11-09 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='organization',
            field=models.CharField(help_text='write full form of the organization', max_length=75, verbose_name='Organization'),
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(choices=[('Agriculture', 'Agriculture'), ('Arts and Entertainment', 'Arts and Entertainment'), ('Education', 'Education'), ('Food', 'Food'), ('Hardware and Automobiles', 'Hardware and Automobiles'), ('Healthcare and Medicine', 'Healthcare and Medicine'), ('Law and Enforcement', 'Law and Enforcement'), ('Sales and Management', 'Sales and Management'), ('Science and Technology', 'Science and Technology')], max_length=100, verbose_name='Interest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interest',
                'verbose_name_plural': 'Interests',
            },
        ),
    ]
