# Generated by Django 3.1.2 on 2020-11-10 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('code', models.UUIDField(primary_key=True, serialize=False, unique=True, verbose_name='Code')),
                ('type', models.CharField(choices=[('Regular', 'Regular'), ('Education', 'Educational'), ('Organization', 'Organization')], max_length=50, verbose_name='Type')),
                ('name', models.CharField(max_length=50, verbose_name='Group Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('link', models.SlugField(verbose_name='Link')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
        ),
    ]
