# Generated by Django 3.1.2 on 2020-11-12 00:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Code')),
                ('type', models.CharField(choices=[('Regular', 'Regular'), ('Education', 'Educational'), ('Organization', 'Organization')], max_length=50, verbose_name='Type')),
                ('name', models.CharField(max_length=50, verbose_name='Group Name')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('membership_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Membership ID')),
                ('isOwner', models.BooleanField(default=False, verbose_name='Is Owner')),
                ('isAssigner', models.BooleanField(default=False, verbose_name='Is Assigner')),
                ('isManager', models.BooleanField(default=False, verbose_name='Is Manager')),
                ('isActive', models.BooleanField(default=True, verbose_name='Is Active')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group', verbose_name='Group')),
            ],
            options={
                'verbose_name': 'Membership',
                'verbose_name_plural': 'Memberships',
            },
        ),
    ]
