# Generated by Django 3.1.2 on 2020-11-10 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='link',
        ),
    ]
