# Generated by Django 3.1.2 on 2020-11-11 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0003_auto_20201111_0906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('membership_id', models.IntegerField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Membership ID')),
                ('isOwner', models.BooleanField(default=False, verbose_name='Is Owner')),
                ('isAssigner', models.BooleanField(default=False, verbose_name='Is Assigner')),
                ('isManager', models.BooleanField(default=False, verbose_name='Is Manager')),
                ('isActive', models.BooleanField(default=True, verbose_name='Is Active')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group', verbose_name='Group')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Member')),
            ],
            options={
                'verbose_name': 'Membership',
                'verbose_name_plural': 'Memberships',
                'unique_together': {('group', 'member')},
            },
        ),
    ]
