# Generated by Django 3.1.2 on 2020-11-11 12:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Membership ID'),
        ),
    ]
